name: test

on:
  pull_request

jobs:
  deno-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno task test
      - run: deno run -A ./testInCompile.ts
      - run: deno compile -A --output exeFile ./testInCompile.ts
      - run: ./exeFile
