name: test

on:
  pull_request

jobs:
  deno-test-compile:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno run -A npm:playwright install
      - run: deno compile -A --output exeFile ./testInCompile.ts
      - run: ./exeFile

  deno-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno run -A npm:playwright install
      - run: deno task test
