name: test

on:
  pull_request

jobs:
  deno-test-compile:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno compile -A --output exeFile ./testInCompile.ts
      - run: ./exeFile

  deno-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: > 
          apt-get update && apt-get install --no-install-recommends -y
          curl=8.5.0-2ubuntu10.1
          ca-certificates=20240203
          unzip=6.0-28ubuntu4
          chromium-browser=2:1snap1-0ubuntu2
        if: matrix.os == 'ubuntu-22.04'
      - run: deno task test
      - run: deno run -A ./testInCompile.ts
